services:
  whiteman:
    build:
      context: app
    volumes:
        - ./log:/app/log
    environment:
      BOT_TOKEN: 
      MC_HOST: 
      MC_PASSWORD: 
      MC_PROTOCOL: 765
      TZ: Asia/Tokyo
    restart: always
