version: '3.7'
services:
  whiteman:
    build:
      context: app
    volumes:
        - ./log:/app/log
    environment:
      BOT_TOKEN: 
      MC_HOST: 
      MC_PASSWORD: 
    networks:
      app_net:
    restart: always

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
